# rename this file to config.toml to use with arle
# config file for arle

title = "Arle bot"

[arle]
version = "0.0.0"
log_level = "debug"
log_file = "arle.log"
local_music = false # when this is true , bot expects music present on local device and enables music features
dev_mode = true

[secrets]
discord_token = ""
genius_token = ""
logfire_token = ""
youtube_api_key = ""
spotify_cid = ""
spotify_cs = ""


[database]

[database.dev]
name = "dev.db"
database_url = "http://127.0.0.1:8080"
database_auth_token = "" # no auth token required with turso for local development

[database.prod]
name = "prod.db"
database_url = ""
database_auth_token = ""
