[project]
name = "arle-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.12.3",
    "libsql-experimental>=0.0.41",
    "logfire[system-metrics]>=2.7.1",
    "loguru>=0.7.2",
    "lyricsgenius>=3.0.1",
    "mutagen>=1.47.0",
    "opentelemetry-instrumentation-aiohttp-client>=0.50b0",
    "opentelemetry-instrumentation-requests>=0.50b0",
    "opentelemetry-instrumentation-sqlite3>=0.50b0",
    "opentelemetry-instrumentation-urllib>=0.50b0",
    "opentelemetry-instrumentation-urllib3>=0.50b0",
    "pillow>=11.0.0",
    "py-cord>=2.6.1",
    "pydantic>=2.10.1",
    "pydub>=0.25.1",
    "pynacl>=1.5.0",
    "requests>=2.32.3",
    "rich>=13.9.4",
    "selenium>=4.26.1",
    "typer>=0.13.1",
]
